# Generated by Django 6.0.5 on 2026-05-05 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeuser',
            name='is_super',
            field=models.BooleanField(default=False),
        ),
    ]
