# Generated by Django 6.0.5 on 2026-05-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0003_rename_is_super_customeuser_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parcel',
            name='delivered_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
