# Generated by Django 6.0.5 on 2026-05-13 22:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveries', '0004_alter_parcel_delivered_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delveryproof',
            name='parcel',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_proof', to='deliveries.parcel'),
        ),
    ]
